var a = 18;
var b = 10;
var c = a - b;
var d = a * b;
var e = a / b;
var f = a % b;
document.write("Subtraction of " + a + " and " + b + " is " +c);
document.write("<br>Multiplication of " + a + " and " + b + " is " +d);
document.write("<br>Division of " + a + " and " + b + " is " +e);
document.write("<br>Modulus of " + a + " and " + b + " is " +f);